<a href="https://colab.research.google.com/github/VuppalapatiJyosthna/DEEP-LEARNING/blob/main/LABASS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1. Single layer perceptron with x=([1 2 3 ],[4 5 6],[7 8 9]) 
                                y=0 1 1 
                                x1=[4 7 8]

In [ ]:
from random import choice

In [ ]:
from numpy import array, dot, random

unit_step = lambda x: 0 if x < 0 else 1

training_data = [
    (array([1,2,3]), 0),
    (array([4,5,6]), 1),
    (array([7,8,9]), 1),
]

w = random.rand(3)
errors = []
eta = 0.2
n = 100

for i in range(n):
    x, expected = choice(training_data)
    result = dot(w, x)
    error = expected - unit_step(result)
    errors.append(error)
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:2], result, unit_step(result)))
    

[1 2]: -0.31544994224315814 -> 0
[4 5]: 0.5050304649029078 -> 1
[7 8]: 1.3255108720489739 -> 1


In [24]:
from numpy import array, dot, random

unit_step = lambda x1: 0 if x1 < 0 else 1

testing_data = [
    (array([4,7,8]), 0),
    
]

w = random.rand(3)
errors = []
eta = 0.2
n = 100

for i in range(n):
    x1, expected = choice(testing_data)
    result = dot(w, x1)
    error = expected - unit_step(result)
    errors.append(error)
    w += eta * error * x1

for x1, _ in testing_data:
    result = dot(x1, w)
    print("{}: {} -> {}".format(x1[:2], result, unit_step(result)))
    

[4 7]: -16.568444038124138 -> 0
